/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  MatchResults,
} from '@stencil/router';
import {
  Post,
} from './types/post';

export namespace Components {
  interface PageAbout {}
  interface PageHome {}
  interface PagePost {
    'match': MatchResults;
  }
  interface PageTag {
    'match': MatchResults;
  }
  interface PostPreview {
    'post': Post;
  }
  interface SiteIndex {}
  interface SiteNav {}
}

declare global {


  interface HTMLPageAboutElement extends Components.PageAbout, HTMLStencilElement {}
  var HTMLPageAboutElement: {
    prototype: HTMLPageAboutElement;
    new (): HTMLPageAboutElement;
  };

  interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {}
  var HTMLPageHomeElement: {
    prototype: HTMLPageHomeElement;
    new (): HTMLPageHomeElement;
  };

  interface HTMLPagePostElement extends Components.PagePost, HTMLStencilElement {}
  var HTMLPagePostElement: {
    prototype: HTMLPagePostElement;
    new (): HTMLPagePostElement;
  };

  interface HTMLPageTagElement extends Components.PageTag, HTMLStencilElement {}
  var HTMLPageTagElement: {
    prototype: HTMLPageTagElement;
    new (): HTMLPageTagElement;
  };

  interface HTMLPostPreviewElement extends Components.PostPreview, HTMLStencilElement {}
  var HTMLPostPreviewElement: {
    prototype: HTMLPostPreviewElement;
    new (): HTMLPostPreviewElement;
  };

  interface HTMLSiteIndexElement extends Components.SiteIndex, HTMLStencilElement {}
  var HTMLSiteIndexElement: {
    prototype: HTMLSiteIndexElement;
    new (): HTMLSiteIndexElement;
  };

  interface HTMLSiteNavElement extends Components.SiteNav, HTMLStencilElement {}
  var HTMLSiteNavElement: {
    prototype: HTMLSiteNavElement;
    new (): HTMLSiteNavElement;
  };
  interface HTMLElementTagNameMap {
    'page-about': HTMLPageAboutElement;
    'page-home': HTMLPageHomeElement;
    'page-post': HTMLPagePostElement;
    'page-tag': HTMLPageTagElement;
    'post-preview': HTMLPostPreviewElement;
    'site-index': HTMLSiteIndexElement;
    'site-nav': HTMLSiteNavElement;
  }
}

declare namespace LocalJSX {
  interface PageAbout {}
  interface PageHome {}
  interface PagePost {
    'match'?: MatchResults;
  }
  interface PageTag {
    'match'?: MatchResults;
  }
  interface PostPreview {
    'post'?: Post;
  }
  interface SiteIndex {}
  interface SiteNav {}

  interface IntrinsicElements {
    'page-about': PageAbout;
    'page-home': PageHome;
    'page-post': PagePost;
    'page-tag': PageTag;
    'post-preview': PostPreview;
    'site-index': SiteIndex;
    'site-nav': SiteNav;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'page-about': LocalJSX.PageAbout & JSXBase.HTMLAttributes<HTMLPageAboutElement>;
      'page-home': LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
      'page-post': LocalJSX.PagePost & JSXBase.HTMLAttributes<HTMLPagePostElement>;
      'page-tag': LocalJSX.PageTag & JSXBase.HTMLAttributes<HTMLPageTagElement>;
      'post-preview': LocalJSX.PostPreview & JSXBase.HTMLAttributes<HTMLPostPreviewElement>;
      'site-index': LocalJSX.SiteIndex & JSXBase.HTMLAttributes<HTMLSiteIndexElement>;
      'site-nav': LocalJSX.SiteNav & JSXBase.HTMLAttributes<HTMLSiteNavElement>;
    }
  }
}


